apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: datacenter
data:
  TIME_FREQ: "8"
---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: datacenter
spec:
  containers:
    - name: time-check
      image: busybox:latest
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            date >> /opt/finance/time/time-check.log
            sleep $TIME_FREQ
          done
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      volumeMounts:
        - name: log-volume
          mountPath: /opt/finance/time
  volumes:
    - name: log-volume
      emptyDir: {}
